Add get subcommand
Add a get subcommand that installs the package into the current workspace. Use go get to install to the external workspace.

diff --git a/gows b/gows
--- a/gows
+++ b/gows
@@ -11,6 +11,7 @@ _gows_help() {
     echo "    cd         switch to directory of package path (default \$GOPATH/src)"
     echo "    edit       open package path in VISUAL editor (default \$GOPATH/src)"
     echo "    env        environment variables for workspace"
+    echo "    get        download and install package to current workspace"
     echo "    init       initialize path as workspace (default working directory)"
     echo "    list       list all workspace paths"
     echo "    reset      reset to empty workspace"
@@ -25,7 +26,7 @@ _gows_help() {
 }
 
 _gows_commands() {
-	for c in run init switch add rm reset list which env edit cd; do
+	for c in add cd edit env get init list reset rm run switch which; do
 		echo $c
 	done
 }
@@ -45,6 +46,58 @@ _gows_complete() {
 	esac
 }
 
+_gows_exec() {
+    case "$1" in
+    add)
+        if [ -z "$2" ]; then
+            _gows_add `_gows_find_ws_path`
+        else
+            _gows_add `_gows_fullpath $2`
+        fi
+        ;;
+    cd)
+    	_gows_cd $2
+    	;;
+    edit)
+        _gows_edit $2
+        ;;
+    get)
+    	_gows_get $2
+    	;;
+    init)
+        if [ -z "$2" ]; then
+            _gows_init $(pwd)
+        else
+            _gows_init `_gows_fullpath $2`
+        fi
+        ;;
+    rm)
+        if [ -z "$2" ]; then
+            _gows_rm `_gows_find_ws_path`
+        else
+            _gows_rm `_gows_fullpath $2`
+        fi
+        ;;
+    switch)
+        if [ -z "$2" ]; then
+            _gows_switch `_gows_find_ws_path`
+        else
+            _gows_switch `_gows_fullpath $2`
+        fi
+        ;;
+    *)
+        echo "Invalid command"
+    esac
+}
+
+_gows_find_ws_path() {
+    local WSPATH=$(pwd)
+    while [[ "$WSPATH" != "" && ! -e "$WSPATH/bin" && ! -e "$WSPATH/pkg" && ! -e "$WSPATH/src" ]]; do
+        WSPATH=${WSPATH%/*}
+    done
+    echo "$WSPATH"
+}
+
 _gows_fullpath() {
   case "$1" in
     /*)
@@ -56,20 +109,63 @@ _gows_fullpath() {
   esac
 }
 
-_gows_find_ws_path() {
-    local WSPATH=$(pwd)
-    while [[ "$WSPATH" != "" && ! -e "$WSPATH/bin" && ! -e "$WSPATH/pkg" && ! -e "$WSPATH/src" ]]; do
-        WSPATH=${WSPATH%/*}
-    done
-    echo "$WSPATH"
-}
-
 _gows_split() {
     OLDIFS="$IFS"
     IFS=$2
     items=(`echo $1`)
     IFS="$OLDIFS"
     echo $items
+}
+
+# Subcommands
+
+_gows_add() {
+    if [[ -n "$1" && -d "$1" ]]; then
+        if [ -z "$_GOWS_OLD_PATH" ]; then
+        	# Workspace has not been set yet
+            _gows_switch $1
+        elif [[ -n "$GOPATH" && ! "$GOPATH" =~  (^|:)"$1"(:|$) ]]; then
+        	# Add workspace if not already on GOPATH
+            GOPATH=$GOPATH:$1
+            export GOPATH
+            
+            PATH=$_GOWS_OLD_PATH:${GOPATH//://bin:}/bin
+            export PATH
+        fi
+    else
+        echo "Go workspace missing"
+    fi
+}
+
+_gows_cd() {
+	cd `_gows_find_ws_path`/src/$1
+	_gows_add `_gows_find_ws_path`
+}
+
+_gows_edit() {
+    if [[ -n "$GOPATH" ]]; then
+		if [ -z "$VISUAL" ]; then
+			echo "VISUAL editor is not set"
+			exit 1
+		fi
+		"$VISUAL" "`_gows_find_ws_path`/src/$1"
+	else
+		echo "Go workspace not set"
+	fi
+}
+
+_gows_env() {
+        echo "GOPATH=$GOPATH"
+        echo "GOROOT=$GOROOT"        
+}
+
+_gows_get() {
+	if [[ -n "$GOPATH" ]]; then
+		# Go get into the current workspace
+		GOPATH=`_gows_find_ws_path` go get $1
+	else
+		echo "Go workspace not set"
+	fi
 }
 
 _gows_init() {
@@ -80,6 +176,49 @@ _gows_init() {
         _gows_add $1
     else
         echo "Path does not exist"
+    fi
+}
+
+_gows_list() {    
+    if [[ -n "$GOPATH" ]]; then
+        items=(`_gows_split $GOPATH ":"`)
+        for item in "${items[@]}"; do
+          echo "$item"
+        done
+    else
+        echo "Go workspace not set"
+    fi
+}
+
+_gows_reset() {
+    if [ -n "$GOPATH" ]; then
+        if [ -n "$_GOWS_OLD_PATH" ]; then
+            PATH=$_GOWS_OLD_PATH
+            export PATH
+            unset _GOWS_OLD_PATH
+        fi
+        if [ -n "$_GOWS_OLD_GOPATH" ]; then
+        	GOPATH=$_GOWS_OLD_GOPATH
+        	export GOPATH
+	        unset _GOWS_OLD_GOPATH
+	    fi
+    else
+        echo "Go workspace not set"
+    fi
+}
+
+_gows_rm() {
+    if [[ -n "$1" && -d "$1" && -n "$GOPATH" && "$GOPATH" =~  (^|:)"$1"(:|$) ]]; then
+        local items=$GOPATH
+        _gows_reset
+        items=(`_gows_split $items ":"`)
+        for item in "${items[@]}"; do
+            if [ "$item" != "$1" ]; then
+                _gows_add $item
+            fi
+        done
+    else
+        echo "Go workspace missing"
     fi
 }
 
@@ -109,143 +248,21 @@ _gows_switch() {
     fi
 }
 
-_gows_add() {
-    if [[ -n "$1" && -d "$1" ]]; then
-        if [ -z "$_GOWS_OLD_PATH" ]; then
-        	# Workspace has not been set yet
-            _gows_switch $1
-        elif [[ -n "$GOPATH" && ! "$GOPATH" =~  (^|:)"$1"(:|$) ]]; then
-        	# Add workspace if not already on GOPATH
-            GOPATH=$GOPATH:$1
-            export GOPATH
-            
-            PATH=$_GOWS_OLD_PATH:${GOPATH//://bin:}/bin
-            export PATH
-        fi
-    else
-        echo "Go workspace missing"
-    fi
-}
-
-_gows_rm() {
-    if [[ -n "$1" && -d "$1" && -n "$GOPATH" && "$GOPATH" =~  (^|:)"$1"(:|$) ]]; then
-        local items=$GOPATH
-        _gows_reset
-        items=(`_gows_split $items ":"`)
-        for item in "${items[@]}"; do
-            if [ "$item" != "$1" ]; then
-                _gows_add $item
-            fi
-        done
-    else
-        echo "Go workspace missing"
-    fi
-}
-
-_gows_reset() {
-    if [ -n "$GOPATH" ]; then
-        if [ -n "$_GOWS_OLD_PATH" ]; then
-            PATH=$_GOWS_OLD_PATH
-            export PATH
-            unset _GOWS_OLD_PATH
-        fi
-        if [ -n "$_GOWS_OLD_GOPATH" ]; then
-        	GOPATH=$_GOWS_OLD_GOPATH
-        	export GOPATH
-	        unset _GOWS_OLD_GOPATH
-	    fi
-    else
-        echo "Go workspace not set"
-    fi
-}
-
-_gows_list() {    
-    if [[ -n "$GOPATH" ]]; then
-        items=(`_gows_split $GOPATH ":"`)
-        for item in "${items[@]}"; do
-          echo "$item"
-        done
-    else
-        echo "Go workspace not set"
-    fi
-}
-
 _gows_which() {
     echo `_gows_find_ws_path`
 }
 
-_gows_env() {
-        echo "GOPATH=$GOPATH"
-        echo "GOROOT=$GOROOT"        
-}
-
-_gows_edit() {
-    if [[ -n "$GOPATH" ]]; then
-		if [ -z "$VISUAL" ]; then
-			echo "VISUAL editor is not set"
-			exit 1
-		fi
-		"$VISUAL" "`_gows_find_ws_path`/src/$1"
-	else
-		echo "Go workspace not set"
-	fi
-}
-
-_gows_cd() {
-	cd `_gows_find_ws_path`/src/$1
-	_gows_add `_gows_find_ws_path`
-}
-
-_gows_exec() {
-    case "$1" in
-    init)
-        if [ -z "$2" ]; then
-            _gows_init $(pwd)
-        else
-            _gows_init `_gows_fullpath $2`
-        fi
-        ;;
-    switch)
-        if [ -z "$2" ]; then
-            _gows_switch `_gows_find_ws_path`
-        else
-            _gows_switch `_gows_fullpath $2`
-        fi
-        ;;
-    add)
-        if [ -z "$2" ]; then
-            _gows_add `_gows_find_ws_path`
-        else
-            _gows_add `_gows_fullpath $2`
-        fi
-        ;;
-    rm)
-        if [ -z "$2" ]; then
-            _gows_rm `_gows_find_ws_path`
-        else
-            _gows_rm `_gows_fullpath $2`
-        fi
-        ;;
-    edit)
-        _gows_edit $2
-        ;;
-    cd)
-    	_gows_cd $2
-    	;;
-    *)
-        echo "Invalid command"
-    esac
-}
+# Command handler
 
 gows() {
     cmd=$1
     
     case "$cmd" in
-    cd | edit | switch)
+    cd | get | edit | switch)
     	_gows_exec $@
         ;;
 	# Can add/remove/init a list of directories
-    add | rm | init)
+    add | get | rm | init)
     	shift
     	if [ $# -gt 0 ]; then
     		while (($#)); do
